### ISSUE TITLE
Call Faucet method

### ISSUE THREAD

**Issue by CrommVardek** [WalChain/walchain#32]
**Question**

Hello, what is correct way to call the faucet ? I guess that through the polkadot.js interface, by using an RPC call to state.call(?, ?, <empty>) the faucet can be called, but what would be the method name and the data to pass ? ("Faucet" and then the account address ? (and what would be the way to derivate a susbtrate address to a "walchain" address ? (nevermind, this is the same as the substrate address))

Thanks !

**Comment by stiiifff** [comment]
First you should install the Polkadot.js browser extension and create a new account.
Then head over to the Polkadot.js UI, and go to the Developer -> Extrinsics tab.
Select your account (that should have been injected by the browser extension), and then the `faucet` pallet and `claimTokens`method. Click the **SubmitTransaction** button, and you should receive 1000 WALC tokens.

**Comment by CrommVardek** [comment]
Thanks, 

However I get the following error : 

-32603: Unknown error occurred: Client, Application, UnknownBlock, State already discarded for BlockId::Hash, 0x909d2bcc45597cb93165711440b0728

**Comment by stiiifff** [comment]
Thx for reporting it, looking into it.

**Comment by CrommVardek** [comment]
From what I quickly read, the issue is that the node is not an archive node. I don't know if that might help however.

**Comment by stiiifff** [comment]
Can you give it another go ?

**Comment by CrommVardek** [comment]
Works fine now, thanks !
